### ISSUE TITLE
Error running the server

### ISSUE THREAD

**Issue by ziky90** [Frankkkkk/docker-overpass-api#1]
Hi,
I'm trying to use the dockerfile, simply by typing `make` and then checking that the DB has loaded by `docker logs` which looks as follows:
```
57274150K .......... .......... .......... .......... .......... 99% 17.7M 0s
57274200K .......... .......... .......... .......... .......... 99%  153M 0s
57274250K .......... ......                                     100%  162M=60m57s

2017-02-06 13:47:14 (15.3 MB/s) - 'planet.osm.bz2' saved [58648848996/58648848996]
```

But I'getting to following problems, when I try url `/api/timestamp`, then:
![screen shot 2017-02-06 at 14 57 19](https://cloud.githubusercontent.com/assets/1810839/22649870/2f0aed18-ec7d-11e6-987b-4b13cbe38cee.png)
 
And when I try url `/api/interpreter`, then:
![screen shot 2017-02-06 at 15 02 38](https://cloud.githubusercontent.com/assets/1810839/22649915/56be02b4-ec7d-11e6-8ccb-e57e57dc8e29.png)

Do you have any idea what could possibly go wrong? Based on the troubleshooting section [here](https://wiki.openstreetmap.org/wiki/Overpass_API/Installation#Troubleshooting) it looks like the dispatcher might not be running.

**Comment by ziky90** [comment]
Sorry, I can see that the server is still loading.

**Comment by Frankkkkk** [comment]
Yeah, maybe we could display a log when the server hasn't loaded yet ?
